### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by DiBeck** [ChristophKirst/SimKernel#10]
Dear all, 

i am trying to use SimKernel in combination with the transferentropy computation from OlavOlav. During compilation by using make, I am runing into the following error:

src/sim.cpp:304:2: fatal error: opening dependency file mpi/sim.d: No such file or directory

and compilation gets terminated. 

I have this issue on mac 10.10.3 and on a Ubuntu 14.04. 
I have no clue why this happens, and i am not so advanced with unix operation system. Would be perfect if you could suport me.

**Comment by orlandi** [comment]
Hi,
That's probably because the mpi folder doesn't exist. Create it with `mkdir mpi` inside the SimKernel folder.

**Comment by DiBeck** [comment]
Hello and thanks for the fast response, 

i added the follter to the SimKernel. The Compilation was running further than before, but still causes an error at a later point. Looks like some funktions are missing. 

 *Undefined symbols for architecture x86_64:
  "Sim::get_expr_nothrow(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ExpressionPtr&, SimSignal const&, bool&)", referenced from:
      bool Sim::get<double>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double&, SimSignal const&) in main.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [exe] Error 1 *

**Comment by orlandi** [comment]
Hi,
I think this is related to issue [https://github.com/ChristophKirst/SimKernel/issues/7] which appears to be fixed in my fork.

Can you try compiling the source from https://github.com/orlandi/SimKernel instead?

**Comment by DiBeck** [comment]
Hi,

i downladed SimKernel from your fork and tried to use make on the virtual Ubuntu system and on the Mac. It does create the same error as discrebed above. However on the unix system i got some more information. At least it seams that the error ocoured in line 60 of the makefile. However i am not sure if that are helpful information. 

*main.cpp:(.text._ZN3Sim3getIdEEbRKSsRT_RK9SimSignal[_ZN3Sim3getIdEEbRKSsRT_RK9SimSignal]+0x4e): Nicht definierter Verweis auf `Sim::get_expr_nothrow(std::string const&, ExpressionPtr&, SimSignal const&, bool&)'
collect2: error: ld returned 1 exit status
Makefile:60: recipe for target 'exe' failed
make: *** [exe] Error 1*

Thanks again for the help.

**Comment by ChristophKirst** [comment]
Hi,

thanks for answering all the questions, what is the fix in your fork ?
I should integrate it in the code...


Hope everything is going well?

Greetings from New York

C.

On 04/18/2015 11:30 AM, Javier G. Orlandi wrote:
>
> Hi,
> I think this is related to issue [#7 
> <https://github.com/ChristophKirst/SimKernel/issues/7>] which appears 
> to be fixed in my fork.
>
> Can you try compiling the source from 
> https://github.com/orlandi/SimKernel instead?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ChristophKirst/SimKernel/issues/10#issuecomment-94174219>.
>

-- 
Christoph Kirst
Fellow for Physics and Biology
Center for Theoretical Studies
The Rockefeller University
1230 York Avenue, New York, NY 10065 USA
+1 212 327 7561 :: ckirst@rockefeller.edu

**Comment by orlandi** [comment]
Hi!
There are two different issues at hand.
The last error from DiBeck is the same as issue https://github.com/ChristophKirst/SimKernel/issues/9 . It is easily fixed by this commit https://github.com/orlandi/SimKernel/commit/20be44476ecbda04b81af28560f0a9ecec34ec02

DiBeck, if you apply this change (you can already pull from my repository) you should be able to compile on Ubuntu (and hopefully also on the mac).

The compilation problems on Mac are related to issue https://github.com/ChristophKirst/SimKernel/issues/7 which I think is also fixed on my repository. The problem is that newer versions of mac use libc++ instead of the libstdc++ as the c++ standard library, and it doesn't like a specific type of forward declarations that SimKernel was using (as far as I have been able to understand).
There are two possible ways to fix this issue:
1. Compile against libstdc++ on osx. But that involves using g++ (since the new g++ in osx is just a wrapper for clang++) and recompiling all possible dependencies on the final program.
2. Move the code around to avoid the forward declaration.

I opted for 2 and implemented it here https://github.com/orlandi/SimKernel/commit/be928f3c17cbd0ad9df3cb3195bb0a11cc224b38
I'm going to do some more testing now (on a fresh mac VM) and create the pull request if everything works.

**Comment by DiBeck** [comment]
Hi again,

thanks for all the help, I just deleted the inline comand in the sim.cpp line 241. Compilation seems to run without error on Mac and Ubuntu. 

The tutorial example did not work yet, but i am not sure if i have time to look into it today. But i will close this issue because compilation seems to work.

**Comment by orlandi** [comment]
Great!
I guess you mean the tutorial from the README. If you were able to compile everything you should also have a test program in the `test` folder. If you run it with `./test input.sim` you should obtain:
```
Sim: It 1: a = 10.4
Sim: It 1: b = 2
Sim: It 1: c = 20
Sim: It 1: a + b = 10.4 + 2 = 12.4
Sim: It 1: Kernel (iteration=1/3) done!
Sim: It 2: a = 10.4
Sim: It 2: b = 2.5
Sim: It 2: c = 20
Sim: It 2: a + b = 10.4 + 2.5 = 12.9
Sim: It 2: Kernel (iteration=2/3) done!
Sim: It 3: a = 10.4
Sim: It 3: b = 3
Sim: It 3: c = 20
Sim: It 3: a + b = 10.4 + 3 = 13.4
Sim: It 3: Kernel (iteration=3/3) done!
Sim: Simulation done!
Sim: 
Sim: Error Summary:
Sim: No errors!
Sim: Bye!
```

Indicating that everything went smooth.
